sudo: false

branches:
  only:
    - master
    - /^greenkeeper/.*$/

language: node_js

matrix:
  include:
    - node_js: "12"
      env: COVERALLS=1

after_success:
  - if [ "x$COVERALLS" = "x1" ]; then npm run coveralls; fi
